### ISSUE TITLE
Throws error

### ISSUE THREAD

**Issue by famishedrover** [samedii/pytorch-zero-lit#1]
`AttributeError: Can't get attribute '_MinExportToOnnx' on <module 'onnx2torch.node_converters.min_max' from '/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/onnx2torch/node_converters/min_max.py'>`

when running : 

```
>>> model = LiT()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/lit/lit.py", line 59, in __init__
    torch.load(self.image_encoder_path).eval().requires_grad_(False)
  File "/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute '_MinExportToOnnx' on <module 'onnx2torch.node_converters.min_max' from '/home/mverma13/.conda/envs/pref39/lib/python3.9/site-packages/onnx2torch/node_converters/min_max.py'>
```

**Comment by famishedrover** [comment]
This is solved by using the correct onnx2torch version 0.15.3 or lower.
